### ISSUE TITLE
'Web3' object has no attribute 'middleware_stack'

### ISSUE THREAD

**Issue by vlukashkinqalab** [ethernity-cloud/etny-node-explorer#2]
python3 nodes_reader.py
Traceback (most recent call last):
  File "nodes_reader.py", line 19, in <module>
    w3.middleware_stack.inject(geth_poa_middleware, layer=0)
AttributeError: 'Web3' object has no attribute 'middleware_stack'

**Comment by florin-nedelcu** [comment]
We'll be posting a new release next week which will fix this issue.

**Comment by ghost** [comment]
Solving the following error:

```
web3.middleware_stack.inject(geth_poa_middleware, layer=0)
AttributeError: 'Web3' object has no attribute 'middleware_stack'
```

Line 19 works fine if web3==4.x.x:

`w3.middleware_stack.inject(geth_poa_middleware, layer=0)`

However, if web3==5.0.1 and later, it should be changed to:

`w3.middleware_onion.inject(geth_poa_middleware, layer=0)`

Ref: https://web3py.readthedocs.io/en/stable/middleware.html#Web3.middleware_onion.add

**Comment by vlukashkinqalab** [comment]
@n05fera2 thank you

pip3 uninstall web3
pip3 install web3==4.10.0

it works now

**Comment by florin-nedelcu** [comment]
now the explorer can be run with both web3 4.* and 5.*
